export const GET_ID_CV = "GET_ID_CV";

export const CHANGE_LANGGUAGE = "CHANGE_LANGGUAGE";
export const CHANGE_COLOR = "CHANGE_COLOR";
export const CHANGE_FONT = "CHANGE_FONT";
export const CHANGE_SIZE = "CHANGE_SIZE";
export const CHANGE_ARROW = "CHANGE_ARROW";

export const FETCH_AWARD = "FETCH_AWARD";
export const ADD_AWARD = "ADD_AWARD";
export const DELETE_AWARD = "DELETE_AWARD";
export const UPDATE_NAME_AWARD = "UPDATE_NAME_AWARD";
export const UPDATE_DAY_AWARD = "UPDATE_DAY_AWARD";
export const UPDATE_TYPE_AWARD = "UPDATE_TYPE_AWARD";
export const UPDATE_BY_AWARD = "UPDATE_BY_AWARD";


export const ADD_CERTIFICATE = "ADD_CERTIFICATE";
export const FETCH_CERTIFICATE = "FETCH_CERTIFICATE";
export const DELETE_CERTIFICATE = "DELETE_CERTIFICATE";
export const UPDATE_NAME_CERTIFICATE = "UPDATE_NAME_CERTIFICATE";
export const UPDATE_DAY_CERTIFICATE = "UPDATE_DAY_CERTIFICATE";
export const UPDATE_CONTENT_CERTIFICATE = "UPDATE_CONTENT_CERTIFICATE";

export const ADD_EDUCATION = "ADD_EDUCATION";
export const FETCH_EDUCATION = "FETCH_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const UPDATE_NAME_EDUCATION = "UPDATE_NAME_EDUCATION";
export const UPDATE_DESCRIPTION_EDUCATION = "UPDATE_DESCRIPTION_EDUCATION";
export const UPDATE_TYPE_EDUCATION = "UPDATE_TYPE_EDUCATION";

export const ADD_LANGUAGE = "ADD_LANGUAGE";
export const FETCH_LANGUAGE = "FETCH_LANGUAGE";
export const DELETE_LANGUAGE = "DELETE_LANGUAGE";
export const UPDATE_NAME_LANGUAGE = "UPDATE_NAME_LANGUAGE";
export const UPDATE_SKILL_LANGUAGE = "UPDATE_SKILL_LANGUAGE";

export const ADD_OBJECTIVE = "ADD_OBJECTIVE";
export const FETCH_OBJECTIVE = "FETCH_OBJECTIVE";
export const DELETE_OBJECTIVE = "DELETE_OBJECTIVE";
export const UPDATE_NAME_OBJECTIVE = "UPDATE_NAME_OBJECTIVE";

export const ADD_ORGANIZATION = "ADD_ORGANIZATION";
export const FETCH_ORGANIZATION = "FETCH_ORGANIZATION";
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";
export const UPDATE_NAME_ORGANIZATION = "UPDATE_NAME_ORGANIZATION";
export const UPDATE_DAY_BEGIN_ORGANIZATION = "UPDATE_DAY_BEGIN_ORGANIZATION";
export const UPDATE_DAY_END_ORGANIZATION = "UPDATE_DAY_END_ORGANIZATION";
export const UPDATE_TYPE_ORGANIZATION = "UPDATE_TYPE_ORGANIZATION";
export const UPDATE_BY_ORGANIZATION = "UPDATE_BY_ORGANIZATION";

export const ADD_PROJECT = "ADD_PROJECT";
export const FETCH_PROJECT = "FETCH_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_NAME_PROJECT = "UPDATE_NAME_PROJECT";
export const UPDATE_DAY_BEGIN_PROJECT = "UPDATE_DAY_BEGIN_PROJECT";
export const UPDATE_DAY_END_PROJECT = "UPDATE_DAY_END_PROJECT";
export const UPDATE_TYPE_PROJECT = "UPDATE_TYPE_PROJECT";
export const UPDATE_BY_PROJECT = "UPDATE_BY_PROJECT";


export const ADD_REFERENCE = "ADD_REFERENCE";
export const FETCH_REFERENCE = "FETCH_REFERENCE";
export const DELETE_REFERENCE = "DELETE_REFERENCE";
export const UPDATE_NAME_REFERENCE = "UPDATE_NAME_REFERENCE";
export const UPDATE_DAY_REFERENCE = "UPDATE_DAY_REFERENCE";
export const UPDATE_PHONE_REFERENCE = "UPDATE_PHONE_REFERENCE";
export const UPDATE_EMAIL_REFERENCE = "UPDATE_EMAIL_REFERENCE";

export const ADD_SKILL = "ADD_SKILL";
export const FETCH_SKILL = "FETCH_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const UPDATE_NAME_SKILL = "UPDATE_NAME_SKILL";
export const UPDATE_NUMBER_SKILL = "UPDATE_NUMBER_SKILL";

export const ADD_SOCIAL = "ADD_SOCIAL";
export const FETCH_SOCIAL = "FETCH_SOCIAL";
export const DELETE_SOCIAL = "DELETE_SOCIAL";
export const UPDATE_NAME_SOCIAL = "UPDATE_NAME_SOCIAL";

export const CHANGE_CV = "CHANGE_CV";
export const SAVE_CV = "SAVE_CV";
export const FETCH_CV = "FETCH_CV";
export const UPDATE_BIRTH_DAY = "UPDATE_BIRTH_DAY";
export const UPDATE_MY_PHONE = "UPDATE_MY_PHONE";
export const UPDATE_MY_ADDRESS = "UPDATE_MY_ADDRESS";
export const UPDATE_MY_EMAIL = "UPDATE_MY_EMAIL";
export const UPDATE_MY_NAME = "UPDATE_MY_NAME";
export const UPDATE_MY_NAMECV = "UPDATE_MY_NAMECV";
export const UPDATE_MY_CHOOSE = "UPDATE_MY_CHOOSE";